
[package]
name = "messaging"
version = "0.1.0"
edition = "2021"

[dependencies]
async-nats = { workspace = true }
tokio = { workspace = true }
common = { path = "../common" }
secrets = { path = "../secrets" }
tokio-stream = "0.1"
serde_json = "1.0"
tracing = { workspace = true }
serde.workspace = true
