
[package]
name = "metrics"
version = "0.1.0"
edition = "2021"

[dependencies]
prometheus = { workspace = true }
common = { path = "../common" }
axum.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true
storage = { version = "0.1.0", path = "../storage" }
opentelemetry = { version = "0.21.0", features = ["trace", "metrics"] }
opentelemetry-otlp = { version = "0.14.0", features = ["tonic"] }
opentelemetry_sdk = { version = "0.21.0", features = ["rt-tokio"] }
tracing-opentelemetry = "0.22.0"
tracing-subscriber.workspace = true
async-nats.workspace = true

[dev-dependencies]
tempfile = "3.27.0"
