[workspace]
resolver = "2"
members = [
    "crates/node",
    "crates/supervisor",
    "crates/runtime",
    "crates/proxy",
    "crates/storage",
    "crates/messaging",
    "crates/secrets",
    "crates/metrics",
    "crates/common",
    "crates/billing",
    "crates/ctl",
    "crates/e2e",
    "crates/vm-testbed",
    "crates/ebpf-monitor",
    "crates/config",
    "crates/internal_gateway",
    "apps/hello-axum",
    "apps/echo-service",
    "apps/postgres-app"
]

[workspace.dependencies]
# Async
tokio        = { version = "1.52", features = ["full"] }

# Serialization
serde        = { version = "1.0", features = ["derive"] }
serde_json   = "1.0"
bincode      = "2.0"

# Error handling
thiserror    = "2.0"
anyhow       = "1.0"

# Logging / Tracing
tracing               = "0.1"
tracing-subscriber    = { version = "0.3", features = ["env-filter", "json"] }

# Wasm runtime
wasmtime              = "43.0.1"
wasmtime-wasi         = "43.0.1"

# Proxy
pingora               = "0.8"
pingora-proxy         = "0.8"
pingora-load-balancing = "0.8"
pingora-core          = "0.8"

# Storage
redb = "4.0"

# Messaging
async-nats = "0.47"

# Encryption
aes-gcm          = "0.10"

# Metrics
prometheus      = { version = "0.14", features = ["process"] }

# HTTP (admin API)
axum = "0.8"

# CLI
clap = { version = "4", features = ["derive", "env"] }

# Utils
uuid   = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }

# Testing
reqwest = { version = "0.13", features = ["json"] }
testcontainers = "0.27"

# Crypto
sha2 = "0.11"
hex = "0.4"

# URL parsing
url = "2"

# Concurrent
dashmap = "6.1"

# eBPF monitoring
aya = "0.12"
aya-log = "0.2"

[profile.release]
opt-level = "s"
lto = true
strip = "symbols"
