
[package]
name = "storage"
version = "0.1.0"
license.workspace = true
edition = "2021"

[dependencies]
redb = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
common = { version = "0.1.0", path = "../common" }
axum = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
tokio = { workspace = true, features = ["full"] }
prometheus = { workspace = true }
async-nats = { workspace = true }
futures = "0.3"
fs2 = "0.4"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["fileapi", "minwindef"] }

[dev-dependencies]
tempfile = "3.27.0"
tokio = { workspace = true, features = ["full"] }
reqwest = { version = "0.13.4", features = ["rustls", "json"], default-features = false }
messaging = { version = "0.1.0", path = "../messaging" }
