[package]
name = "internal_gateway"
version = "0.1.0"
license.workspace = true
edition = "2021"

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
common = { version = "0.1.0", path = "../common" }
supervisor = { version = "0.1.0", path = "../supervisor" }
proxy = { version = "0.1.0", path = "../proxy" }
ebpf-monitor = { version = "0.1.0", path = "../ebpf-monitor" }
chrono = { workspace = true }
http = "1.4.1"
hyper = { version = "1.10.1", features = ["client", "http1", "http2"] }
hyper-util = { version = "0.1.20", features = ["tokio"] }
tower = "0.5.3"
tower-http = { version = "0.6.11", features = ["trace"] }
futures = "0.3.32"

[dev-dependencies]
base64 = "0.22.1"
jsonwebtoken = { workspace = true }
rand = "0.10.1"
rsa = "0.9.10"
