[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
toml = "0.8"
anyhow = { workspace = true }
tracing = { workspace = true }
async-nats = { workspace = true }
common = { path = "../common" }
storage = { path = "../storage" }
metrics = { path = "../metrics" }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
tempfile = "3"
tokio = { workspace = true, features = ["full", "test-util"] }
