[package]
name = "grpc-echo"
version = "0.1.0"
license.workspace = true
edition = "2021"
build = "build.rs"

[dependencies]

[build-dependencies]
tonic-prost-build = "0.14.6"
protoc-bin-vendored = "3.2.0"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tokio = { workspace = true }
tonic = { version = "0.14.6", features = ["transport"] }
tonic-prost = "0.14.2"
prost = "0.14.1"
tokio-stream = { version = "0.1", features = ["net"] }
