
[package]
name = "node"
version = "0.1.0"
license.workspace = true
edition = "2021"

[[bin]]
name = "wasm-node"
path = "src/main.rs"

[features]
ebpf = ["ebpf-monitor/ebpf"]

[dev-dependencies]
e2e = { version = "0.1.0", path = "../e2e" }
uuid = { workspace = true }
serde_json = { workspace = true }
tempfile = "3.27.0"

[dependencies]
argon2 = "0.5.3"
base64 = "0.22.1"
aws-config = "1.8.18"
aws-sdk-kms = "1.110.0"
ureq = { version = "3.3.0", features = ["json"] }
hex = { workspace = true }
sha2 = { workspace = true }
ed25519-dalek = "2.2.0"
chrono = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { workspace = true, features = ["env"] }
anyhow = { workspace = true }
futures = "0.3.32"
axum = { workspace = true }
axum-server = { version = "0.8.0", features = ["tls-rustls"] }
rustls = "0.23.40"
serde = { workspace = true }
serde_json = { workspace = true }
toml = "0.9.8"
common = { version = "0.1.0", path = "../common" }
storage = { version = "0.1.0", path = "../storage" }
runtime = { version = "0.1.0", path = "../runtime" }
supervisor = { version = "0.1.0", path = "../supervisor" }
proxy = { version = "0.1.0", path = "../proxy" }
messaging = { version = "0.1.0", path = "../messaging" }
metrics = { version = "0.1.0", path = "../metrics" }
secrets = { version = "0.1.0", path = "../secrets" }
billing = { version = "0.1.0", path = "../billing" }
async-nats = { workspace = true }
ebpf-monitor = { version = "0.1.0", path = "../ebpf-monitor" }
config = { version = "0.1.0", path = "../config" }
internal_gateway = { version = "0.1.0", path = "../internal_gateway" }
