
[package]
name = "billing"
version = "0.1.0"
license.workspace = true
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
common = { version = "0.1.0", path = "../common" }
storage = { version = "0.1.0", path = "../storage" }
async-trait = "0.1.92"
chrono = { workspace = true }
reqwest = { workspace = true }

[dev-dependencies]
tempfile = "3.27.0"
