[package]
name    = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde       = { workspace = true }
serde_json  = { workspace = true }
thiserror   = { workspace = true }
uuid        = { workspace = true }
chrono      = { workspace = true }
sha2        = { workspace = true }
hex         = { workspace = true }
ipnet       = "2.12.0"
