
[package]
name = "supervisor"
version = "0.1.0"
license.workspace = true
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = "0.1.92"
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
common = { version = "0.1.0", path = "../common" }
runtime = { version = "0.1.0", path = "../runtime" }
storage = { version = "0.1.0", path = "../storage" }
secrets = { version = "0.1.0", path = "../secrets" }
metrics = { version = "0.1.0", path = "../metrics" }
billing = { version = "0.1.0", path = "../billing" }
ebpf-monitor = { version = "0.1.0", path = "../ebpf-monitor" }
messaging = { version = "0.1.0", path = "../messaging" }
proxy = { version = "0.1.0", path = "../proxy" }
uuid.workspace = true
reqwest = { workspace = true }
libc = "0.2.189"

[dev-dependencies]
tempfile = "3.27.0"
wat = "1.256.0"
