[package]
name = "postgres-app"
version = "0.1.0"
license.workspace = true
edition = "2021"

[dependencies]
url = { workspace = true }
serde_json = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
axum = { workspace = true }
tokio = { workspace = true }
wasi-pg-client = { version = "0.2.0", features = ["tokio-transport"] }

[target.'cfg(target_family = "wasm")'.dependencies]
wasi-pg-client = "0.2.0"
wstd = "0.6"
