
[package]
name = "hello-axum"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hello-axum"
path = "src/main.rs"

[dependencies]
axum = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tokio = { workspace = true }

[target.'cfg(target_family = "wasm")'.dependencies]
tokio = { version = "1", features = ["sync", "macros", "io-util", "rt", "time"] }

[profile.release]
opt-level = 3
lto = true
strip = "symbols"
