
[package]
name = "proxy"
version = "0.1.0"
license.workspace = true
edition = "2021"

[dependencies]
pingora = { workspace = true }
pingora-proxy = { workspace = true }
pingora-load-balancing = { workspace = true }
pingora-core = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = "0.33.0"
opentelemetry = { version = "0.32.0", features = ["trace"] }
common = { version = "0.1.0", path = "../common" }
async-trait = "0.1.92"
futures = "0.3.34"
axum.workspace = true
serde_json.workspace = true
storage = { version = "0.1.0", path = "../storage" }
prometheus = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
messaging = { version = "0.1.0", path = "../messaging" }
dashmap = { workspace = true }
rand = "0.10.2"
hex = { workspace = true }
chrono = { workspace = true }
jsonwebtoken = { workspace = true }
async-nats = { workspace = true }
http = "1.5.0"
sha2 = { workspace = true }

[dev-dependencies]
tower = "0.5.3"
e2e = { version = "0.1.0", path = "../e2e" }
aws-lc-rs = "1.17.0"
base64 = "0.23.1"
pkcs8 = "0.10.2"
