
[package]
name = "proxy"
version = "0.1.0"
license.workspace = true
edition = "2021"

[dependencies]
pingora = { workspace = true }
pingora-proxy = { workspace = true }
pingora-load-balancing = { workspace = true }
pingora-core = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
common = { version = "0.1.0", path = "../common" }
async-trait = "0.1.89"
futures = "0.3.32"
axum.workspace = true
serde_json.workspace = true
storage = { version = "0.1.0", path = "../storage" }
prometheus = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
messaging = { version = "0.1.0", path = "../messaging" }
dashmap = { workspace = true }
rand = "0.10"
hex = { workspace = true }
chrono = { workspace = true }
jsonwebtoken = "9"
async-nats = { workspace = true }
http = "1"
sha2 = { workspace = true }

[dev-dependencies]
tower = "0.5"
rsa = "0.9"
base64 = "0.22"
e2e = { version = "0.1.0", path = "../e2e" }
