[package]
name = "ebpf-monitor"
version = "0.1.0"
license.workspace = true
edition = "2021"

[features]
default = []
ebpf = ["dep:aya", "dep:aya-log"]

[dependencies]
aya = { version = "0.13.1", optional = true }
aya-log = { version = "0.2", optional = true }
common = { version = "0.1.0", path = "../common" }
metrics = { version = "0.1.0", path = "../metrics" }
prometheus = { version = "0.14", features = ["process"] }
tokio = { version = "1.52", features = ["full"] }
tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = { workspace = true }
libc = "0.2"

[dev-dependencies]
tokio = { version = "1.52", features = ["full", "test-util"] }
