[package]
name = "ebpf-monitor"
version = "0.1.0"
license.workspace = true
edition = "2021"

[[example]]
name = "load_probe"
required-features = ["ebpf"]

[features]
default = []
ebpf = ["dep:aya", "dep:aya-log"]

[dependencies]
aya = { version = "0.14.0", optional = true }
aya-log = { version = "0.3.0", optional = true }
common = { version = "0.1.0", path = "../common" }
metrics = { version = "0.1.0", path = "../metrics" }
prometheus = { version = "0.14.0", features = ["process"] }
tokio = { version = "1.53.1", features = ["full"] }
tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = { workspace = true }
libc = "0.2.189"

[dev-dependencies]
tokio = { version = "1.53.1", features = ["full", "test-util"] }
tracing-subscriber.workspace = true
